drop table journal;
drop table persons;
create table persons (
       id NUMBER GENERATED by default on null as IDENTITY,
       name VARCHAR2(150),
       CONSTRAINT persons_pk PRIMARY KEY (id)
    );
COMMENT ON TABLE persons IS 'Сотрудники';
comment on column persons.id is 'Идентификатор сотрудника';
comment on column persons.name is 'ФИО сотрудника';
create table journal (
       id NUMBER GENERATED by default on null as IDENTITY,
       person number,
       DTime date,
       Type varchar2(1) CHECK(Type in ('0','1')),
       CONSTRAINT fk_persons
         FOREIGN KEY (person)
         REFERENCES persons(id)
    );
COMMENT ON TABLE journal IS 'Таблица "Журнал входов выходов"';
comment on column journal.id is 'Идентификатор записи в журнале';
comment on column journal.person is 'Идентификатор сотрудника';
comment on column journal.DTime is 'Дата и время события';
comment on column journal.Type is 'Тип события: ''0'' – вход, ''1'' – выход';
commit;
